name: API Tests with Newman

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🧪 Install Newman CLI
        run: npm install -g newman

      - name: 🚀 Run API Tests
        run: |
          newman run postman/collection.json
